#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@cloudflare-ddns[-1]
	add ucitrack cloudflare-ddns
	set ucitrack.@cloudflare-ddns[-1].init=cloudflare-ddns
	commit ucitrack
EOF

# 删除LuCI缓存
rm -rf /tmp/luci-*
exit 0 
