#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@cloudflare-ddns[-1]
	add ucitrack cloudflare-ddns
	set ucitrack.@cloudflare-ddns[-1].init=cloudflare-ddns
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0 
