#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /bin/sh -c "while true; do /usr/bin/cloudflare-ddns-update; sleep \$(uci -q get cloudflare-ddns.config.update_interval); done"
    procd_set_param respawn
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger "cloudflare-ddns"
} 
