name: Build OpenWrt Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup OpenWrt SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ccache ecj fastjar file g++ gawk \
        gettext git java-propose-classpath libelf-dev libncurses5-dev \
        libncursesw5-dev libssl-dev python3 python3-dev unzip wget \
        python3-pip python3-setuptools rsync subversion \
        swig time xsltproc zlib1g-dev
        
        wget https://downloads.openwrt.org/releases/22.03.5/targets/x86/64/openwrt-sdk-22.03.5-x86-64_gcc-11.2.0_musl.Linux-x86_64.tar.xz
        tar xf openwrt-sdk-22.03.5-x86-64_gcc-11.2.0_musl.Linux-x86_64.tar.xz
        mv openwrt-sdk-22.03.5-x86-64_gcc-11.2.0_musl.Linux-x86_64 sdk
        
        cd sdk
        
        mkdir -p logs
        
        ./scripts/feeds update -a 2>&1 | tee logs/feeds-update.log
        ./scripts/feeds install -a 2>&1 | tee logs/feeds-install.log
        
        make tools/install -j$(nproc) 2>&1 | tee logs/tools-install.log
        make toolchain/install -j$(nproc) 2>&1 | tee logs/toolchain-install.log
        
        cat >> .config <<EOF
        CONFIG_PACKAGE_luci-app-cloudflare-ddns=y
        CONFIG_PACKAGE_curl=y
        CONFIG_PACKAGE_lua=y
        CONFIG_PACKAGE_luci-base=y
        CONFIG_PACKAGE_luci=y
        CONFIG_PACKAGE_luci-mod-admin-full=y
        CONFIG_PACKAGE_luci-lib-base=y
        CONFIG_PACKAGE_luci-lib-ip=y
        CONFIG_PACKAGE_luci-lib-jsonc=y
        CONFIG_PACKAGE_luci-lib-nixio=y
        CONFIG_ALL_NONSHARED=y
        CONFIG_ALL=y
        EOF
        
        make defconfig 2>&1 | tee logs/defconfig.log
    
    - name: Copy Package Files
      run: |
        mkdir -p sdk/package/luci-app-cloudflare-ddns
        cp -r luasrc root Makefile sdk/package/luci-app-cloudflare-ddns/
    
    - name: Build Package
      run: |
        cd sdk
        make package/luci-app-cloudflare-ddns/compile V=s -j$(nproc) 2>&1 | tee logs/compile.log || {
          echo "Build failed. Check the logs for details."
          exit 1
        }
        
        # 显示编译后的文件
        echo "=== Built files ==="
        find . -type f -name "*.ipk"
        echo "=================="
    
    - name: Find and Upload IPK
      run: |
        cd sdk
        # 搜索所有可能的目录
        IPK_FILES=$(find . -type f -name "luci-app-cloudflare-ddns*.ipk")
        if [ -z "$IPK_FILES" ]; then
          echo "No IPK files found!"
          echo "Directory contents:"
          ls -R bin/ || echo "bin/ directory not found"
          ls -R staging_dir/ || echo "staging_dir/ directory not found"
          ls -R build_dir/ || echo "build_dir/ directory not found"
          exit 1
        else
          echo "Found IPK files:"
          echo "$IPK_FILES"
          # 创建临时目录存放IPK文件
          mkdir -p ipk-files
          # 复制找到的所有IPK文件
          for ipk in $IPK_FILES; do
            cp "$ipk" ipk-files/
          done
        fi
    
    - name: Upload IPK
      uses: actions/upload-artifact@v3
      with:
        name: luci-app-cloudflare-ddns
        path: sdk/ipk-files/*.ipk
    
    - name: Upload Build Logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: build-logs
        path: sdk/logs/ 
