name: Build OpenWrt Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup OpenWrt SDK
      run: |
        # 下载并解压 OpenWrt SDK
        wget https://downloads.openwrt.org/releases/22.03.5/targets/x86/64/openwrt-sdk-22.03.5-x86-64_gcc-11.2.0_musl.Linux-x86_64.tar.xz
        ls -la
        tar xf openwrt-sdk-22.03.5-x86-64_gcc-11.2.0_musl.Linux-x86_64.tar.xz
        ls -la
        SDK_DIR=$(ls -d openwrt-sdk-*)
        echo "Found SDK directory: $SDK_DIR"
        mv "$SDK_DIR" sdk
        ls -la
        
    - name: Prepare Package
      run: |
        ls -la
        echo "Creating package directory..."
        mkdir -p sdk/package/luci-app-cloudflare-ddns
        echo "Copying files..."
        cp -rv Makefile luasrc root sdk/package/luci-app-cloudflare-ddns/
        echo "Listing package directory..."
        ls -la sdk/package/luci-app-cloudflare-ddns/
        
    - name: Install Dependencies
      run: |
        cd sdk
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        
    - name: Build Package
      run: |
        cd sdk
        make defconfig
        make package/luci-app-cloudflare-ddns/compile V=s
        
    - name: Upload IPK
      uses: actions/upload-artifact@v3
      with:
        name: luci-app-cloudflare-ddns
        path: sdk/bin/packages/*/base/luci-app-cloudflare-ddns_*.ipk
        
    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        files: sdk/bin/packages/*/base/luci-app-cloudflare-ddns_*.ipk
        tag_name: v${{ github.run_number }}
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
